### ISSUE TITLE
Summary data inaccessible for individual health units 

### ISSUE THREAD

**Issue by some-molasses** [ccodwg/CovidTimelineCanada#32]
Hello,

## Issue
The API query to get summary data for specific health units is returning an `HTTPValidationError` of `"Invalid loc"`.  

## Replicating
This issue can be replicated in the query builder [here](https://api.opencovid.ca/#/) or simply though the url string.

Here's a sample URL for Middlesex London (`hruid` 3544): `https://api.opencovid.ca/summary?geo=hr&loc=[3544]`.

Would you be able to look into it?

thanks!

**Comment by jeanpaulrsoucy** [comment]
Two issues here:

1. The syntax for providing parameters where there is the possibility of multiple items is like such:

`https://api.opencovid.ca/summary?geo=hr&loc=3544`

with multiple entries being provided like such:

`https://api.opencovid.ca/summary?geo=hr&loc=3544&loc=3526`

This isn't super intuitive so I will try to improve this with better documentation & examples.

2. Health region filter really *was* broken, though, as you discovered using the query builder. This is now fixed by ccodwg/Covid19CanadaAPI@903d1e4d520920e3a47f32f8ef86c33c2af9fd8c. Apologies for this---I really need to write some tests for the API to prevent basic features from breaking.

Please let me know if this fixes your issue & if you have any others.

**Comment by some-molasses** [comment]
This has resolved the issue.  Thank you for the clarification on the input syntax and quick resolution time!
