### ISSUE TITLE
DISCUSSION: What are the most important values to report?

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/CovidTimelineCanada#7]
What are the core values for COVID-19 that reporting should focus on? My current thinking:

- Cases
- Deaths
- Number of tests (and combined with above, % positivity)
- Vaccine coverage (1st, 2nd, 3rd doses)
- Hospitalizations
- ICU

I would argue that active/recovered case numbers are not particularly relevant, as they are essentially lagged case numbers. There is also the issue of the definition of recovered differing between regions and over time. Finally, some places have stopped reporting active/recovered values, like [BC did on 2022-02-10](https://twitter.com/richardzussman/status/1491911075352113154) (but they will [continue to report cases, deaths, hospitalizations and ICU](https://twitter.com/richardzussman/status/1491915429840781316)).

Vaccine coverage (1st, 2nd, 3rd doses) is also more relevant than raw dose numbers.

**Comment by mister-elliott** [comment]
Are the provinces providing data enough to allow you to report your six values above with total, daily AND those values with  a consistent set of age-range breakdowns, say by decades. (and by gender). 
Is it possible to get vaccination status for hospitalizations and ICU and death?
I know the provinces are tardy or reluctant or incapable to report, so less data but of high quality/accuracy might be the goal.

**Comment by rogadev** [comment]
Depending on your use case, one could argue that all of the above are important.

For what I'm building, the reports of active case numbers and change from the last report are the most important. I'm using these numbers to compare to provincial population to give users a visual representation of the "hottest" provinces in Canada, at a glance. I should say I WAS using these numbers until they evaporated in the most recent update of the API.

While I know that provinces are not equal when it comes to data accuracy and reporting quality, especially as apathy towards COVID19 grows, even rough data is useful. A 7-day average may be the best way to get a sense of changes in case numbers, instead of daily numbers, because I know that most provinces (for example) don't seem to report over the weekends. So rather than a massive spike on Monday, you'd see a slight dip Saturday, Sunday, then a jump back to a more accurate number on Monday. I think 7-day trends should be something to implement, certainly.

I don't know how much work it would be to bring active_cases and active_cases_change values back but I personally sure would appreciate it, as my app is essentially useless without them.

**Comment by jeanpaulrsoucy** [comment]
To keep this issue updated, as mentioned in the other thread (https://github.com/ccodwg/Covid19CanadaAPI/issues/31#issuecomment-1120279595), a majority (7/13) of jurisdictions have stopped reporting active/recovered case numbers altogether:

- AB
- BC
- MB
- NL
- NS
- NU
- SK
